# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MCUX-SDK-CodingStyleChecker.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_codingRuleSetting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_codingRuleSetting.setGeometry(QtCore.QRect(10, 10, 81, 51))
        self.pushButton_codingRuleSetting.setObjectName("pushButton_codingRuleSetting")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 70, 781, 411))
        self.textEdit_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_log.setObjectName("textEdit_log")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 490, 781, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.textEdit_fileFolderFilter = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_fileFolderFilter.setGeometry(QtCore.QRect(190, 40, 441, 21))
        self.textEdit_fileFolderFilter.setObjectName("textEdit_fileFolderFilter")
        self.label_fileFolderFilter = QtWidgets.QLabel(self.centralwidget)
        self.label_fileFolderFilter.setGeometry(QtCore.QRect(100, 30, 91, 31))
        self.label_fileFolderFilter.setObjectName("label_fileFolderFilter")
        self.textEdit_inputFileFolder = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_inputFileFolder.setGeometry(QtCore.QRect(190, 10, 441, 21))
        self.textEdit_inputFileFolder.setObjectName("textEdit_inputFileFolder")
        self.label_selectFileFolder = QtWidgets.QLabel(self.centralwidget)
        self.label_selectFileFolder.setGeometry(QtCore.QRect(100, 0, 91, 31))
        self.label_selectFileFolder.setObjectName("label_selectFileFolder")
        self.pushButton_browseFileFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browseFileFolder.setGeometry(QtCore.QRect(640, 10, 71, 21))
        self.pushButton_browseFileFolder.setObjectName("pushButton_browseFileFolder")
        self.checkBox_isFolder = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_isFolder.setGeometry(QtCore.QRect(720, 10, 61, 21))
        self.checkBox_isFolder.setObjectName("checkBox_isFolder")
        self.pushButton_doCheck = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_doCheck.setGeometry(QtCore.QRect(640, 40, 71, 21))
        self.pushButton_doCheck.setObjectName("pushButton_doCheck")
        self.pushButton_saveLog = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveLog.setGeometry(QtCore.QRect(720, 40, 71, 21))
        self.pushButton_saveLog.setObjectName("pushButton_saveLog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMenuHelpHomePage = QtWidgets.QAction(MainWindow)
        self.actionMenuHelpHomePage.setAutoRepeat(True)
        self.actionMenuHelpHomePage.setObjectName("actionMenuHelpHomePage")
        self.actionMenuHelpAboutAuthor = QtWidgets.QAction(MainWindow)
        self.actionMenuHelpAboutAuthor.setObjectName("actionMenuHelpAboutAuthor")
        self.actionMenuHelpRevisionHistory = QtWidgets.QAction(MainWindow)
        self.actionMenuHelpRevisionHistory.setObjectName("actionMenuHelpRevisionHistory")
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionMenuHelpHomePage)
        self.menuHelp.addAction(self.actionMenuHelpAboutAuthor)
        self.menuHelp.addAction(self.actionMenuHelpRevisionHistory)
        self.menuHelp.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCUXpresso SDK Coding Style Checker"))
        self.pushButton_codingRuleSetting.setText(_translate("MainWindow", "Coding Rule \n"
"\n"
" Setting"))
        self.label_fileFolderFilter.setText(_translate("MainWindow", "File/Folder Filter:"))
        self.label_selectFileFolder.setText(_translate("MainWindow", "Select File/Folder:"))
        self.pushButton_browseFileFolder.setText(_translate("MainWindow", "Browse"))
        self.checkBox_isFolder.setText(_translate("MainWindow", "Is Folder"))
        self.pushButton_doCheck.setText(_translate("MainWindow", "Check"))
        self.pushButton_saveLog.setText(_translate("MainWindow", "Save Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionMenuHelpHomePage.setText(_translate("MainWindow", "Home Page"))
        self.actionMenuHelpAboutAuthor.setText(_translate("MainWindow", "About Author"))
        self.actionMenuHelpRevisionHistory.setText(_translate("MainWindow", "Revision History"))

